/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-06 01:04:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agregar_005fprofesor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Document</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/ins_profesor.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       \n");
      out.write("        <nav>\n");
      out.write("                <input type=\"checkbox\" id=\"check\">\n");
      out.write("                <label for=\"check\" class=\"checkbtn\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("                \n");
      out.write("                </label>\n");
      out.write("                <a href=\"\" class=\"enlace\">\n");
      out.write("                    <img src=\"imagen/demo.png\" alt=\"\" class=\"logo\">\n");
      out.write("                </a>\n");
      out.write("                <ul>\n");
      out.write("                 <li><a href=\"ServDestroy\">inicio</a></li>\n");
      out.write("               <li><a href=\"noticias.php\">noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("                    </nav>\n");
      out.write("           ");

           HttpSession sesion=request.getSession();
           
        String rel=(String)sesion.getAttribute("session_logSe");
         if(sesion.getAttribute("session_logSe")==null){
             response.sendRedirect("login.jsp");
             }
             
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("          \n");
      out.write("            <div class=\"lateral\">\n");
      out.write("    <div class=\"option\">\n");
      out.write("   \n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"acceso_SE.jsp\">\n");
      out.write("            <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                <h4>pricipal</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"incidencias.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>  incidencias profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"alumnos.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> alumnos</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"profesor.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"colegiatura.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> Colegiaturas</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"inscripcion.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> inscripciones</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"body\">\n");
      out.write("        \n");
      out.write("            <div class=\"formulario\">\n");
      out.write("            <form action=\"ServProfesor\" method=\"POST\">\n");
      out.write("            <div class=\"inputa\">\n");
      out.write("            <h2>   <a href=\"profesor.jsp\">Consultar Profesor</a></h2>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("            <div class=\"form_grupo\">\n");
      out.write("           <label class=\"form_label\" for=\"nombre\">Nombre</label>\n");
      out.write("                <input type=\"text\" id=\"nombre\" name=\"nombre\" placeholder=\"ingrese nombre\" > \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form_grupo\">\n");
      out.write("           <label class=\"form_label\" for=\"apellidoP\">Apellido Paterno</label>\n");
      out.write("                <input type=\"text\" id=\"apellidoP\" name=\"apellidoP\" placeholder=\"ingrese apellido\" > \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form_grupo\">\n");
      out.write("           <label class=\"form_label\" for=\"apellidoM\">Apellido Materno</label>\n");
      out.write("                <input type=\"text\" id=\"apellidoM\" name=\"apellidoM\" placeholder=\"ingrese apellido\" > \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form_grupo\">\n");
      out.write("           <label class=\"form_label\" for=\"email\">Email</label>\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"ingrese email\" > \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form_grupo\">\n");
      out.write("           <label class=\"form_label\" for=\"matricula\">Matricula</label>\n");
      out.write("                <input type=\"text\" id=\"matricula\" name=\"matricula\" placeholder=\"ingrese matricula\" > \n");
      out.write("                </div>\n");
      out.write("             \n");
      out.write("             \n");
      out.write("                    <div class=\"inputa\">\n");
      out.write("                    <button  class=\"button2\" type=\"submit\" name=\"btn_envia\">guardar</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("             \n");
      out.write("                    <script>\n");
      out.write("    \n");
      out.write("alert(\"debe llenar todos los campos\");\n");
      out.write("                    </script>\n");
      out.write("               \n");
      out.write("                      <script>alert(\"la matricula  ya se encuentran en la BD\")</script>\n");
      out.write("                \n");
      out.write("                    <script>alert(\"el email ya se encuentran en la BD\")</script>\n");
      out.write("                \n");
      out.write("                      <script>alert(\"datos ingresados correctamente\")</script>\n");
      out.write("                 \n");
      out.write("                      <script>alert(\"error al ingresar datos \")</script>\n");
      out.write("               \n");
      out.write("             </div>\n");
      out.write("             </div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("        \n");
      out.write("        <script href=\"javascript/profesor.js\"></script>\n");
      out.write("  \n");
      out.write("          \n");
      out.write("        </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
