/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-31 02:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import modelo.Profesor;
import java.util.List;
import modeloDAO.ProfesorDao;

public final class agregar_005fasignatura_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("modelo.Profesor");
    _jspx_imports_classes.add("modeloDAO.ProfesorDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Document</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/ins_profesor.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <nav>\n");
      out.write("                <input type=\"checkbox\" id=\"check\">\n");
      out.write("                <label for=\"check\" class=\"checkbtn\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("                \n");
      out.write("                </label>\n");
      out.write("                <a href=\"\" class=\"enlace\">\n");
      out.write("                    <img src=\"imagen/demo.png\" alt=\"\" class=\"logo\">\n");
      out.write("                </a>\n");
      out.write("                <ul>\n");
      out.write("               \n");
      out.write("              \n");
      out.write("               \n");
      out.write("             \n");
      out.write("               \n");
      out.write("               \n");
      out.write("                <li><a href=\"ServDestroy\">inicio</a></li>\n");
      out.write("               \n");
      out.write("                <li><a href=\"noticias.jsp\">noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("                    </nav>\n");
      out.write("            <div class=\"container\">\n");
      out.write("          \n");
      out.write("            <div class=\"lateral\">\n");
      out.write("    <div class=\"option\">\n");
      out.write("   \n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"acceso_SE.php\">\n");
      out.write("            <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                <h4>pricipal</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"incidencia.php\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>  incidencias </h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"alumnos.php\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> alumnos</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"profesor.php\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"colegiatura.php\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>Colegiatura</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"inscripcion.php\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> inscripciones</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"body\">\n");
      out.write("        \n");
      out.write("            <div class=\"formulario\">\n");
      out.write("            <form action=\"ServMuestraInscr1\" method=\"POST\">\n");
      out.write("            <div class=\"inputa\">\n");
      out.write("            <h2>   <a href=\"inscripcion.jsp\">Consultar asignatura</a></h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form_grupo\">\n");
      out.write("           \n");
      out.write("                <label class=\"form_label\" for=\"matricula\">Asignatura</label>\n");
      out.write("                <input type=\"text\" id=\"asigntura\" name=\"asignatura\" placeholder=\"ingrese asignatura\" > \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("             <div class=\"form_grupo\">\n");
      out.write("             <label class=\"form_label\" for=\"grupo\">Profesor</label> \n");
      out.write("         \n");
      out.write("                     <select name=\"profesor\" id=\"profesor\">\n");
      out.write("                     <option value=\"Elige una opcion\">elige una opcion</option>\n");
      out.write("                 \n");
      out.write("                    ");

                    ProfesorDao dao=new ProfesorDao();
                
                    List<Profesor>prof=dao.mostrarProfesorU();
                    Iterator<Profesor>itera=prof.iterator();
                    Profesor p= null;
                    while (itera.hasNext()) {
                            p=itera.next();
                 
      out.write("\n");
      out.write("                 <option value=");
      out.print(p.getId());
      out.write('>');
      out.print(p.getNombre()+" "+p.getApellido()+" "+p.getApellido_materno());
      out.write("</option>\n");
      out.write("  \n");
      out.write("                             ");
}
      out.write("\n");
      out.write("      </select>\n");
      out.write("      <label class=\"form_label\" for=\"nivel\">Nivel Academico</label> \n");
      out.write("      <select name=\"nivel_academico\" id=\"nivel_academico\">\n");
      out.write("<option value=\"Elige una opcion\">Elige una Opcion</option>\n");
      out.write("<option value=\"Preescolar\">Preescolar</option>\n");
      out.write("<option value=\"Primaria\">Primaria</option>\n");
      out.write("<option value=\"Secundaria\">Secundaria</option>\n");
      out.write("<option value=\"Preparatoria\">Preparatoria</option>\n");
      out.write("\n");
      out.write("      </select>\n");
      out.write("             </div>\n");
      out.write("                    <div class=\"inputa\">\n");
      out.write("                    <button  class=\"button2\" type=\"submit\" name=\"btn_envia\">guardar</button>\n");
      out.write("                    </div>\n");
      out.write("                    <h2 class=\"form_elimina\" for=\"grupo\">Eliminar asignatura</h2> \n");
      out.write("                </form>\n");
      out.write("                <div class=\"elimina\">\n");
      out.write("                <form action=\"ServMuestraInscr1\" class=\"form_grupo\" method=\"POST\">\n");
      out.write("                 \n");
      out.write("                \n");
      out.write("                  <select name=\"asig\" id=\"asig\">\n");
      out.write("                  <option value=\"elige unan opcion\">elige una opcion</option>\n");
      out.write("          \n");
      out.write("                 \n");
      out.write("                  ");

                  ProfesorDao d=new ProfesorDao();
                  List<Profesor>pr=d.mostrarProfesor();
                  Iterator<Profesor>it=pr.iterator();
                  Profesor pro=null;
                  while (it.hasNext()) {
                          pro=it.next();
                         
      out.write("\n");
      out.write("                         <option value=");
      out.print(pro.getId_asignatura());
      out.write('>');
      out.print(pro.getAsignatura()+" profesor "+pro.getNombre()+" "+pro.getApellido()+" "+pro.getApellido_materno());
      out.write("</option>\n");
      out.write("          ");
}
      out.write("\n");
      out.write("   </select>\n");
      out.write("<button class=\"boton\"  name=\"btn_elimina\" id=\"grupo\">ELIMINAR</button>\n");
      out.write("              </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("                   <script>alert('asignatura eliminada correctamente')</script>\n");
      out.write("               \n");
      out.write("                    <script>alert(\"ingrese una asignatura\")</script>\n");
      out.write("                \n");
      out.write("             </div>\n");
      out.write("             </div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("        \n");
      out.write("    \n");
      out.write("    \n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("        </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
