/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-07 05:05:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.List;
import modelo.Alumno;
import modeloDAO.AlumnoDao;

public final class alumnos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("modeloDAO.AlumnoDao");
    _jspx_imports_classes.add("modelo.Alumno");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Alumno</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/alumno_estilo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <script src=\"alumno.js\"></script>\n");
      out.write("        <nav>\n");
      out.write("                <input type=\"checkbox\" id=\"check\">\n");
      out.write("                <label for=\"check\" class=\"checkbtn\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("                \n");
      out.write("                </label>\n");
      out.write("                <a href=\"\" class=\"enlace\">\n");
      out.write("                    <img src=\"imagen/demo.png\" alt=\"\" class=\"logo\">\n");
      out.write("                </a>\n");
      out.write("                <ul>\n");
      out.write("              \n");
      out.write("                <li><a href=\"ServDestroy\">inicio</a></li>\n");
      out.write("                <li><a href=\"noticias.jsp\">noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("                    </nav>\n");
      out.write("           ");

           HttpSession sesion=request.getSession();
           
        String rel=(String)sesion.getAttribute("session_logSe");
         if(sesion.getAttribute("session_logSe")==null){
             response.sendRedirect("login.jsp");
             }
             
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("    <div class=\"lateral\">\n");
      out.write("   \n");
      out.write("    <div class=\"option\">\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"acceso_SE.jsp\">\n");
      out.write("            <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                <h4>pricipal</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"incidencia.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>  incidencias </h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"alumnos.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> alumnos</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"profesor.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"colegiatura.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> Colegiaturas</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"inscripcion.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> inscripciones</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"body\">\n");
      out.write("           <div class=\"left\">\n");
      out.write("            <div class=\"form_grupo\">\n");
      out.write("            <div class=\"grupo_form\">\n");
      out.write("                <div class=\"selects\">\n");
      out.write("                <form action=\"ServAlumno\" class=\"form_grupo\" method=\"GET\">\n");
      out.write("                <label class=\"form_label\" for=\"grupo\">nivel educativo</label> \n");
      out.write("                    <select name=\"nivel_1\" id=\"nivel_1\">\n");
      out.write("                    <option value=\"selecciona\">selecciona un nivel</option>\n");
      out.write("                    <option value=\"preescolar\">preescolar</option>\n");
      out.write("                    <option value=\"primaria\">primaria</option>\n");
      out.write("                    <option value=\"secundaria\">secundaria</option>\n");
      out.write("                    <option value=\"preparatoria\">preparatoria</option>\n");
      out.write("                    </select>\n");
      out.write("                    <label class=\"form_label\" for=\"grupo\">grupo</label> \n");
      out.write("                <select name=\"grupo\" id=\"grupo\">\n");
      out.write("                <option value=\"selecciona\">selecciona un grupo</option>\n");
      out.write("                    <option value=\"1-A\">1-A</option>\n");
      out.write("                    <option value=\"1-B\">1-B</option>\n");
      out.write("                    <option value=\"1-C\">1-C</option>\n");
      out.write("                    <option value=\"2-A\">2-A</option>\n");
      out.write("                    <option value=\"2-B\">2-B</option>\n");
      out.write("                    <option value=\"2-C\">2-C</option>\n");
      out.write("                    <option value=\"3-A\">3-A</option>\n");
      out.write("                    <option value=\"3-B\">3-B</option>\n");
      out.write("                    <option value=\"3-C\">3-C</option>\n");
      out.write("                    <option value=\"4-A\">4-A</option>\n");
      out.write("                    <option value=\"4-B\">4-B</option>\n");
      out.write("                    <option value=\"4-C\">4-C</option>\n");
      out.write("                    <option value=\"5-A\">5-A</option>\n");
      out.write("                    <option value=\"5-B\">5-B</option>\n");
      out.write("                    <option value=\"5-C\">5-C</option>\n");
      out.write("                    <option value=\"6-A\">6-A</option>\n");
      out.write("                    <option value=\"6-B\">6-B</option>\n");
      out.write("                    <option value=\"6-C\">6-C</option>\n");
      out.write("                 </select>\n");
      out.write("                 </div>\n");
      out.write("                <button class=\"btn_sel\"  name=\"btn_grupo\" id=\"grupo\">buscar</button>\n");
      out.write("                 </form>\n");
      out.write("                </div>\n");
      out.write("              \n");
      out.write("                <form class=\"nuevos\" action=\"ServAlumno\" class=\"form_grupo\">\n");
      out.write("                    <label class=\"form_label\" for=\"nivel\">nuevos usuarios</label> \n");
      out.write("                    <button class=\"btn_sel\" name=\"btn_user\" id=\"btn_user\">buscar</button>\n");
      out.write("            </form>\n");
      out.write("                \n");
      out.write("               </div>\n");
      out.write("            \n");
      out.write("                \n");
      out.write("                <table class=\"tabla\" id=\"data-table\">\n");
      out.write("                    <tr>\n");
      out.write("                        <th>matricula</th>\n");
      out.write("                        <th colspan=\"2\">nombre</th>\n");
      out.write("                        <th>email</th>\n");
      out.write("                         <th>usuario</th>\n");
      out.write("                        <th>turno</th>\n");
      out.write("                       <th>nivel </th>\n");
      out.write("                        <th>grupo</th>\n");
      out.write("                        <th>Editar</th>\n");
      out.write("                        </tr>\n");
      out.write("                    ");

                      
                       List<Alumno> al=null;
                      
                         Iterator<Alumno>itera=null;
                        String r=(String)request.getAttribute("user");
                    
                        String niv=(String)request.getAttribute("nivel");
                            String gru=(String)request.getAttribute("grup");
                        
                    AlumnoDao dao= new AlumnoDao();
                    if(niv!=null&&gru!=null){
                       al=dao.showAlumn( gru,niv);
                    }else{
                     al=dao.showAlumn();
                    }
                   
                      
                         itera=al.iterator(); 
                    
                    Alumno per=null;
                    while (itera.hasNext()) {
                            per=itera.next();
                        
                    
      out.write("\n");
      out.write("              \n");
      out.write("                        <tr>\n");
      out.write("                        <td data-titulo=\"matricula\">");
      out.print(per.getMatricula());
      out.write("</td>\n");
      out.write("                            <td data-titulo=\"nombre\" colspan=\"2\">");
      out.print(per.getNombre());
      out.write("</td>\n");
      out.write("                     \n");
      out.write("                            <td data-titulo=\"email\">");
      out.print(per.getEmail());
      out.write("</td>\n");
      out.write("                            <td data-titulo=\"turno\">");
      out.print(per.getTurno());
      out.write("</td>\n");
      out.write("                            \n");
      out.write("                            <td data-titulo=\"tipo usuario\">");
      out.print(per.getTipo_usuario());
      out.write("</td>\n");
      out.write("                            <td data-titulo=\"nivel educativo\">");
      out.print(per.getNivel_educativo());
      out.write("</td>\n");
      out.write("                            <td data-titulo=\"grupo\">");
      out.print(per.getGrupo());
      out.write("</td>\n");
      out.write("                            <td><button class=\"boton\"><a  href=\"ServAlumno?txtID=");
      out.print(per.getId());
      out.write("\" >editar</a></button>\n");
      out.write("    \n");
      out.write("                        </tr>\n");
      out.write("                 \n");
      out.write("                        ");
}
                        
      out.write("\n");
      out.write("                   \n");
      out.write("                </table>\n");
      out.write("       \n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("           </div>\n");
      out.write("    \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
