/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-06 17:20:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import modelo.Incidence_al;
import modeloDAO.Incidence_al_dao;
import java.util.Iterator;
import modelo.Incidence_prof;
import java.util.List;
import modeloDAO.Incidence_prof_dao;
import modelo.Incidence;
import modeloDAO.IncidenceDao;

public final class incidencia_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("modelo.Incidence_prof");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("modelo.Incidence");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("modeloDAO.Incidence_al_dao");
    _jspx_imports_classes.add("modeloDAO.Incidence_prof_dao");
    _jspx_imports_classes.add("modelo.Incidence_al");
    _jspx_imports_classes.add("modeloDAO.IncidenceDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Document</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/style_incidencia.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <nav>\n");
      out.write("                <input type=\"checkbox\" id=\"check\">\n");
      out.write("                <label for=\"check\" class=\"checkbtn\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("                \n");
      out.write("                </label>\n");
      out.write("                <a href=\"\" class=\"enlace\">\n");
      out.write("                    <img src=\"imagen/demo.png\" alt=\"\" class=\"logo\">\n");
      out.write("                </a>\n");
      out.write("                <ul>\n");
      out.write("           \n");
      out.write("               \n");
      out.write("             \n");
      out.write("               \n");
      out.write("               \n");
      out.write("                <li><a href=\"ServDestroy\">inicio</a></li>\n");
      out.write("               \n");
      out.write("                <li><a href=\"noticias.jsp\">noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("                    </nav>\n");
      out.write("           ");

           HttpSession sesion=request.getSession();
           
        String rel=(String)sesion.getAttribute("session_logSe");
         if(sesion.getAttribute("session_logSe")==null){
             response.sendRedirect("login.jsp");
             }
             
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("           \n");
      out.write("            <div class=\"lateral\">\n");
      out.write("            <div class=\"option\">\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"acceso_SE.jsp\">\n");
      out.write("            <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                <h4>pricipal</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"incidencia.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>  incidencias </h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"alumnos.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> alumnos</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"profesor.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"colegiatura.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> Colegiaturas</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"inscripcion.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> inscripciones</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"body\">\n");
      out.write("               <div class=\"left\">\n");
      out.write("               \n");
      out.write("        <div class=\"form_group\">\n");
      out.write("\n");
      out.write("            <form method=\"GET\" action=\"ServIncidence\">\n");
      out.write("                <h3>incidencias</h3>\n");
      out.write("                <label for=\"alumno\">Alumnos</label>\n");
      out.write("                <input type=\"radio\" name=\"opcion\" value=\"alumno\">\n");
      out.write("               <label for=\"prof\">Profesores</label>\n");
      out.write("               <input type=\"radio\" name=\"opcion\" value=\"profesor\" >\n");
      out.write("               <label for=\"se\">General</label>\n");
      out.write("              <input type=\"radio\" name=\"opcion\" value=\"SE\" ><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<input type=\"date\" name=\"f1\" placeholder=\"fecha inicio\">\n");
      out.write("<input type=\"date\" name=\"f2\" placeholder=\"fecha fin\">\n");
      out.write("<input type=\"text\" name=\"matricula\" placeholder=\"matricula\">\n");
      out.write("<button  class=\"boton\" name=\"btn_check_fecha\">Buscar</button>\n");
      out.write("</form>\n");
      out.write("               <button class=\"btn_lat\"><a href=\"agregar_incidencia.jsp\"><h2>Agregar </h2></a></button>\n");
      out.write("        </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"right\">\n");
      out.write("                  <table>\n");
      out.write("                   \n");
      out.write("                    <tr>\n");
      out.write("                        <th colspan=\"2\">Nombre</th>\n");
      out.write("                        <th>Incidecnia</th>\n");
      out.write("                        <th>Fecha</th>\n");
      out.write("                        <th>Editar</th>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                        
                    
                       String f1=(String)request.getAttribute("ff1");
                        String f2=(String)request.getAttribute("ff2");
                          String matricula=(String)request.getAttribute("matr");
                          String opcion=(String)request.getAttribute("opc");
                  
                          
                          Incidence_prof_dao dao_prof=new Incidence_prof_dao();
                          List<Incidence_prof> inci=dao_prof.mostrarIncidence(f1, f2,matricula);
                          List<Incidence_prof> inciX=dao_prof.mostrarIncidence(f1, f2);
                          Iterator <Incidence_prof>itera_prof=inci.iterator();
                            Iterator <Incidence_prof>itera_profX=inciX.iterator();
                      
                           Incidence_al_dao dao_al=new Incidence_al_dao();
                           List<Incidence_al> inci_al=dao_al.mostrarIncidence(f1, f2,matricula);
                           List<Incidence_al> inci_alX=dao_al.mostrarIncidence(f1, f2);
                           Iterator<Incidence_al>itera_al=inci_al.iterator();
                            Iterator<Incidence_al>itera_alX=inci_alX.iterator();
                           
                            IncidenceDao dao_se= new IncidenceDao();
                            List<Incidence> inci_se=dao_se.mostrarIncidence(f1, f2);
                            Iterator<Incidence>itera=inci_se.iterator();
                      
                         
                    
                        Incidence_prof profX=null;
                        Incidence_al alumno=null;
                          Incidence_prof profY=null;
                        Incidence_al alumnoY=null;
                        Incidence SE=null;
                          while (itera_prof.hasNext()&&opcion.equalsIgnoreCase("profesor")) {
                         
                         profX=itera_prof.next();
                         
                         

      out.write("\n");
      out.write("                         <tr>\n");
      out.write("                          <td>");
      out.print(profX.getNombre());
      out.write("</td> \n");
      out.write("                             <td>");
      out.print(profX.getIncidence());
      out.write("</td> \n");
      out.write("                            <td>");
      out.print("fecha "+profX.getDate1());
      out.write("</td>\n");
      out.write("                                <td><button class=\"boton\"><a href=\"ServIncidence?ProfId_incidence=");
      out.print(profX.getId());
      out.write("\" >Editar</a></button></td>\n");
      out.write("                             </tr>\n");
      out.write("          \n");
      out.write("    \n");
      out.write("                       ");
}  while (itera_al.hasNext()&&opcion.equalsIgnoreCase("alumno")) {
                         
                         alumno=itera_al.next();
                         
                         

      out.write("\n");
      out.write("                         <tr>\n");
      out.write("                          <td>");
      out.print(alumno.getNombre());
      out.write("</td>\n");
      out.write("                           \n");
      out.write("                          <td>");
      out.print(alumno.getIncidence());
      out.write("</td>\n");
      out.write("                            <td>");
      out.print("fecha "+alumno.getDate1());
      out.write("</td>\n");
      out.write("                          <td><button class=\"boton\"><a href=\"ServIncidence?AlumnoId_incidence=");
      out.print(alumno.getId());
      out.write("\" >Editar</a></button></td>\n");
      out.write("                             </tr>\n");
      out.write("          \n");
      out.write("    \n");
      out.write("                       ");
}  while (itera.hasNext()&&opcion.equalsIgnoreCase("SE")) {
                         
                         SE=itera.next();
                         
                         

      out.write("\n");
      out.write("                         <tr>\n");
      out.write("                          <td>");
      out.print(SE.getNombre());
      out.write("</td>\n");
      out.write("                             <td>");
      out.print(SE.getIncidence());
      out.write("</td>\n");
      out.write("                                <td>");
      out.print("fecha "+SE.getDate1());
      out.write("</td>\n");
      out.write("                                <td><button class=\"boton\"><a href=\"ServIncidence?SeId_incidence=");
      out.print(SE.getId());
      out.write("\" >Editar</a></button></td>\n");
      out.write("                             </tr>\n");
      out.write("          \n");
      out.write("    \n");
      out.write("                       ");
}while (itera_profX.hasNext()&&opcion.equalsIgnoreCase("profesor")&&matricula.isEmpty()) {
                         
                         profX=itera_profX.next();
                         
                         

      out.write("\n");
      out.write("                         <tr>\n");
      out.write("                          <td>");
      out.print(profX.getNombre());
      out.write("</td>\n");
      out.write("                             <td>");
      out.print(profX.getIncidence());
      out.write("</td>\n");
      out.write("                               <td>");
      out.print("fecha "+profX.getDate1());
      out.write("</td>\n");
      out.write("                             <td><button class=\"boton\"><a href=\"ServIncidence?ProfId_incidence=");
      out.print(profX.getId());
      out.write("\" >Editar</a></button></td>\n");
      out.write("                             </tr>\n");
      out.write("          \n");
      out.write("    \n");
      out.write("                       ");
}   while (itera_alX.hasNext()&&opcion.equalsIgnoreCase("alumno")&&matricula.isEmpty()) {
                         
                         alumno=itera_alX.next();
                         
                         

      out.write("\n");
      out.write("                         <tr>\n");
      out.write("                          <td>");
      out.print(alumno.getNombre());
      out.write("</td>\n");
      out.write("                           <td>");
      out.print(alumno.getIncidence());
      out.write("</td>\n");
      out.write("                           <td>");
      out.print("fecha "+alumno.getDate1());
      out.write("</td>\n");
      out.write("                                <td><button class=\"boton\"><a href=\"ServIncidence?AlumnoId_incidence=");
      out.print(alumno.getId());
      out.write("\" >Editar</a></button></td>\n");
      out.write("                             </tr>\n");
      out.write("          \n");
      out.write("    \n");
      out.write("                       ");
}
                       
                       
      out.write("\n");
      out.write("                 \n");
      out.write("                      \n");
      out.write("                  </table>\n");
      out.write("                \n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("       \n");
      out.write("   \n");
      out.write("    \n");
      out.write("          \n");
      out.write("        </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
