/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-31 02:45:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Document</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/estylo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <nav>\n");
      out.write("    <input type=\"checkbox\" id=\"check\">\n");
      out.write("    <label for=\"check\" class=\"checkbtn\">\n");
      out.write("    <i class=\"fas fa-bars\"></i>\n");
      out.write("    \n");
      out.write("    </label>\n");
      out.write("    <a href=\"\" class=\"enlace\">\n");
      out.write("        <img src=\"imagen/demo.jpg\" alt=\"\" class=\"logo\">\n");
      out.write("    </a>\n");
      out.write("    <ul>\n");
      out.write("    <li><a href=\"index.html\">inicio</a></li>\n");
      out.write("    <li><a href=\"registrarse.jsp\">registrarse</a></li>\n");
      out.write("    <li><a href=\"login.jsp\">login</a></li>\n");
      out.write("    </ul>\n");
      out.write("        </nav>\n");
      out.write("        <section class=\"center\">\n");
      out.write("            <h1> Educacion Especial <p>ABC</p></h1>\n");
      out.write("            \n");
      out.write("        \n");
      out.write("        </section>\n");
      out.write("         <div class=\"container\">\n");
      out.write("\n");
      out.write("            <div class=\"boxt\">\n");
      out.write("  <img class=\"imagen1\" src=\"imagen/prepa.jpg\" alt=\"\" width=\"100%\">\n");
      out.write("    <div class=\"imagen\">\n");
      out.write("       <p class=\"img-1\">  En Educacion especial ABC, estamos comprometidos a brindar educación de calidad a niños de todas las capacidades.\n");
      out.write("         Nuestro equipo de maestros experimentados y dedicados trabaja incansablemente para crear un entorno de aprendizaje inclusivo\n");
      out.write("          y de apoyo que ayude a cada estudiante a alcanzar su máximo potencial. <br>\n");
      out.write("          Nuestro personal está formado por profesionales altamente calificados apasionados por su trabajo y comprometidos a ayudar\n");
      out.write("           a cada estudiante a alcanzar su máximo potencial.\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    <div class=\"boxt\">\n");
      out.write("<div class=\"imagen\">\n");
      out.write("        <p class=\"img-1\"> \n");
      out.write("            es importante que los estudiantes obtengan las habilidades necesarias que pide el mundo como cualquier persona que esta aprendiendo\n");
      out.write("            como las reglas de nuestro lenguaje (gramatica) aritmetica basica de manera que se totalmente entendible y usada en su mundo real ademas \n");
      out.write("            tambien nos enfocamos en su desarrollo social como personas integrantes de una sociedad y hacerlse saber que tienen los mismos derechos \n");
      out.write("            constitucionales , las diferencia ? las diferencias las tenemos cada unos de nosotros ya que somos seres unicos e irrepetibles , nos enfocamos\n");
      out.write("            de igual manera en su desarrollo emocional respetar el espacio de otras personas y asi mismo que se respete su propio espacio ,alegrias tristesa \n");
      out.write("            miedos todos los tenemos y no es malo expresar nuestras emociones y deseos \n");
      out.write("         </p>\n");
      out.write("     </div>\n");
      out.write("     <img class=\"imagen1\" src=\"imagen/prepa.jpg\" alt=\"\" width=\"100%\">\n");
      out.write("     </div>\n");
      out.write("     <div class=\"boxt\">\n");
      out.write("        <img class=\"imagen1\" src=\"imagen/prepa.jpg\" alt=\"\" width=\"100%\">\n");
      out.write("          <div class=\"imagen\">\n");
      out.write("             <p class=\"img-1\">  En Educacion especial ABC, estamos comprometidos a brindar educación de calidad a niños de todas las capacidades.\n");
      out.write("               Nuestro equipo de maestros experimentados y dedicados trabaja incansablemente para crear un entorno de aprendizaje inclusivo\n");
      out.write("                y de apoyo que ayude a cada estudiante a alcanzar su máximo potencial. <br>\n");
      out.write("                Nuestro personal está formado por profesionales altamente calificados apasionados por su trabajo y comprometidos a ayudar\n");
      out.write("                 a cada estudiante a alcanzar su máximo potencial.\n");
      out.write("              </p>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"boxt\">\n");
      out.write("       \n");
      out.write("          <div class=\"imagen\">\n");
      out.write("             <p class=\"img-1\"> Muchos padres de familia y tutores de nuestros estudiantes atestiguan los cambios positivos que han \n");
      out.write("                notado en sus niños nuestros estudiantes en sus habilidades de aprendizaje notorios en su capacidad lectora su diccion en el \n");
      out.write("                habla , su emocion por ser los primeros en querer asistir a clases por ser un espacion donde se sienten motivados y el aprender \n");
      out.write("                lo toman como algo agradable y divertido ,en su adaptacion en entornos sociales  aumenta notablemente su capacidad de comunicacion \n");
      out.write("                con otras personas , entendiendo de esta forma que la educacion es muy importante para su futuro.\n");
      out.write("              </p>\n");
      out.write("          </div>\n");
      out.write("          <img class=\"imagen1\" src=\"imagen/prepa.jpg\" alt=\"\" width=\"100%\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("        <footer class=\"pie-pagina\">\n");
      out.write("    <div class=\"grupo-1\">\n");
      out.write("    <div class=\"box\">\n");
      out.write("    <figure>\n");
      out.write("        <a href=\"#\">\n");
      out.write("            <img src=\"imagen/edu.jpg\" alt=\"logo\">\n");
      out.write("        </a>\n");
      out.write("    </figure>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"box\">\n");
      out.write("        <h3>SOBRE NOSOTROS</h3>\n");
      out.write("        <p>somos una institucion que reconocemos el valor unico de cada niño <br>\n");
      out.write("            por lo que nuestar tarea principal es conocer a cada uno de nuestros <br>\n");
      out.write("            estudiantes y proporcionarles la estrategia de aprendizaje mas<br>\n");
      out.write("             adecuada que ellos necesitan \n");
      out.write("        </p>\n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("    <div class=\"box\">\n");
      out.write("   <h3>SIGUENOS</h3>\n");
      out.write("        <div class=\"red-social\">\n");
      out.write("            <a href=\"#\" class=\"fa fa-facebook\"></a>\n");
      out.write("            <a href=\"#\" class=\"fa fa-instagram\"></a>\n");
      out.write("            <a href=\"#\" class=\"fa fa-twitter\"></a>\n");
      out.write("            <a href=\"#\" class=\"fa fa-youtube\"></a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"grupo-2\">\n");
      out.write("        <small>&copy; 2023 <b>Educacion Especial</b> - Todos los Derechos Reservados-</small>\n");
      out.write("    </div>\n");
      out.write("        </footer>\n");
      out.write("    \n");
      out.write("\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
