/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-12 00:22:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.ArrayList;
import modelo.Asignatura_inscripcion;
import java.util.List;
import modeloDAO.AsignaturaInscrDao;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import config.Conexion;

public final class inscripcion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("config.Conexion");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("modeloDAO.AsignaturaInscrDao");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("modelo.Asignatura_inscripcion");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Document</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/style_asignatura.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("        <script src=\"https://kit.fontawesome.com/6a4751c08d.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <nav>\n");
      out.write("                <input type=\"checkbox\" id=\"check\">\n");
      out.write("                <label for=\"check\" class=\"checkbtn\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("                \n");
      out.write("                </label>\n");
      out.write("                <a href=\"\" class=\"enlace\">\n");
      out.write("                    <img src=\"imagen/demo.png\" alt=\"\" class=\"logo\">\n");
      out.write("                </a>\n");
      out.write("                <ul>\n");
      out.write("               <li><a href=\"ServDestroy\">inicio</a></li>\n");
      out.write("                <li><a href=\"noticias.jsp\">noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("                    </nav>\n");
      out.write("           ");

           HttpSession sesion=request.getSession();
           
        String rel=(String)sesion.getAttribute("session_logSe");
         if(sesion.getAttribute("session_logSe")==null){
             response.sendRedirect("login.jsp");
             }
             
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("          \n");
      out.write("            <div class=\"lateral\">\n");
      out.write("           \n");
      out.write("    <div class=\"option\">\n");
      out.write("   \n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"acceso_SE.jsp\">\n");
      out.write("            <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                <h4>pricipal</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("        <a href=\"incidencia.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>  incidencias </h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"alumnos.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> alumnos</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"profesor.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4>profesores</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"colegiatura.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> Colegiaturas</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logotipo\">\n");
      out.write("            <a href=\"inscripcion.jsp\">\n");
      out.write("                <i class=\"fa-sharp fa-regular fa-calendar-days\"></i>\n");
      out.write("                <h4> inscripciones</h4>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"body\">\n");
      out.write("           \n");
      out.write("            <div class=\"filt\">\n");
      out.write("                <div class=\"encabezado\">\n");
      out.write("                <h2>consultas de alumnos elige una opcion   </h2>\n");
      out.write("               \n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("                <form action=\"ServMuestraInscr1\" class=\"form_grupo\" method=\"GET\">\n");
      out.write("                 \n");
      out.write("                    <label class=\"form_label\" for=\"grupo\">asignatura</label> \n");
      out.write("                \n");
      out.write("                   \n");
      out.write("                     <select name=\"asignatura\" id=\"asignatura\">\n");
      out.write("                     <option value=\"elige unan opcion\"></option>\n");
      out.write("                           ");

         
                      
                      Conexion con = new Conexion();
                      Connection cnx=con.conectar();
                       try{
                      PreparedStatement pst;
                      ResultSet rs;
           pst=cnx.prepareStatement("select asig.asignatura,prof.nombre,prof.apellidoP,prof.apellidoM from asignatura"
                   + "  asig inner join profesor prof on asig.id_profesor=prof.id_profesor");
           rs=pst.executeQuery();
           while (rs.next()) {
               
      out.write("\n");
      out.write("               <option value=\"");
      out.print(rs.getString("asignatura"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("asignatura")+rs.getString("nombre"));
      out.write("</option>\n");
      out.write("             ");

              
                            
           }
         
       } catch (Exception ex) {
         
       }
                 
               
      out.write(" \n");
      out.write("                    \n");
      out.write("                     \n");
      out.write("                   \n");
      out.write("\n");
      out.write("      </select>\n");
      out.write("<button class=\"boton\"  name=\"btn_asignatura\" id=\"grupo\">buscar</button>\n");
      out.write("                 </form>\n");
      out.write("            \n");
      out.write("                <form action=\"ServMuestraInscr1\" class=\"form_grupo\" method=\"GET\">\n");
      out.write("                 \n");
      out.write("                    <label class=\"form_label\" for=\"nivel\">matricula del alumno</label> \n");
      out.write("                  <input type=\"text\" name=\"matricula\">\n");
      out.write("                        <button class=\"boton\"  name=\"btn_matricula\" id=\"btn_matricula\">buscar</button>\n");
      out.write("            </form>\n");
      out.write("            <div class=\"tab\">\n");
      out.write("            <table>\n");
      out.write("          \n");
      out.write("            <tr>\n");
      out.write("                <th colspan=\"2\">Nombre</th>\n");
      out.write("                \n");
      out.write("                <th>Asignatura</th>\n");
      out.write("                <th>Estatus</th>\n");
      out.write("                <th>Editar</th>\n");
      out.write("            </tr>\n");
      out.write("           ");

                Iterator<Asignatura_inscripcion>iter=null;
                      String asignature=(String)request.getAttribute("asignaturaEnviada");
                       String matricula=(String)request.getAttribute("matriculaEnviada");
                      AsignaturaInscrDao dao=new AsignaturaInscrDao();
                      if(asignature!=null){
                           List<Asignatura_inscripcion>asig=dao.listaAsignaturas(asignature);
                              
                           iter=asig.iterator();
                      }else{
                   
                     List<Asignatura_inscripcion>matr=dao.listaMatricula(matricula);
                    iter=matr.iterator();
                      }
                        Asignatura_inscripcion per=null;
                     while (iter.hasNext()) {
                             per=iter.next();
                               
      out.write("\n");
      out.write("                                 <tr>\n");
      out.write("                              <td colspan=\"2\">");
      out.print(per.getNombre());
      out.write("</td>\n");
      out.write("                              \n");
      out.write("                                    <td>");
      out.print(per.getAsignatura());
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(per.getEstatus());
      out.write("</td>\n");
      out.write("                            <td><button class=\"boton\"><a  href=\"ServMuestraInscr1?txtID=");
      out.print(per.getId());
      out.write("\" >Editar</a></button>\n");
      out.write("                        </tr>\n");
      out.write("                     ");

                     }
                     
      out.write("\n");
      out.write("                  </table> \n");
      out.write("            </div>\n");
      out.write("             </div>\n");
      out.write("           </div>\n");
      out.write("     </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
